# config/algs/gat_ac_3m.yaml

name: "enhanced_gat_3m_dqn"

#########################################
# 1) 環境
#########################################
env: "sc2"                # 代表 StarCraft II 環境
env_args:
  map_name: "3m"          # 3 Marine vs 3 Marine
  difficulty: "7"         # 難度 (1~10) or "7" => Hard
  # 其他 SMAC 相關參數，如
  obs_all_health: True
  obs_own_health: True
  # ...
  # 你之前自訂的: 會在 get_state() 生 54維的 state (6 node x 9 dim)
  debug: False

#########################################
# 2) 多智能體 參數
#########################################
agent: "enhanced_gat_agent"     # 要對應 modules/agents/__init__.py REGISTRY
mac:   "enhanced_gat_mac"       # 要對應 controllers/__init__.py REGISTRY

# 選擇 Q-learning => agent_output_type = "q"
agent_output_type: "q"

# 選擇 QLearner => PyMARL 內建 "q_learner"
learner: "q_learner"

#mixer: null
#mixer: "qmix"
#mixer: "gpqmix"
mixer: "qmeta"
#因應qmix
mixing_embed_dim: 32
hypernet_embed: 64
hypernet_layers: 2
#########################################
# 3) GAT 相關參數
#########################################
gat_node_input_dim: 9   # node_feats ( health, shield, type, pos_x, pos_y, cooldown, ... ), total=9
gat_edge_input_dim: 3   # e.g. [dist, visibility, attackable]
gat_hidden_dim: 32      # hidden dim

#########################################
# 4) Exploration (epsilon-greedy)
#########################################
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000  # 幾個 steps 內線性遞減
test_greedy: True           # 測試時用 greedy

#########################################
# 5) 訓練超參數
#########################################
# 你可根據需要調整
t_max: 100000          # 最多 step
batch_size: 32
buffer_size: 5000
burn_in_period: 32
gamma: 0.99
lr: 0.0005            # learning rate for agent
grad_norm_clip: 10

# target_update_interval: 200  # 也可在 default.yaml or q_learner.py 預設
double_q: True        # 是否用Double Q

#########################################
# 6) 其他
#########################################
runner: "episode"           # 單環境, episode_runner
batch_size_run: 1           # 并行環境=1
test_nepisode: 20           # 每次測試episode數
test_interval: 2000         # 幾個timesteps後測試
log_interval: 2000          # Log訓練信息

use_cuda: True              # 是否用GPU
save_model: False           # 若要存model,可改 True
save_model_interval: 200000

#checkpoint_path: "C:/Users/hsk/Desktop/python/pymarl/results/models/enhanced_gat_3m_dqn__2025-02-03_15-16-42"
#load_step: 3002153

#checkpoint_path: ""
#load_step: ""
evaluate: False
target_update_interval: 200
