name: "gat_qmix_3m"

env: "sc2"
env_args:
  map_name: "3m"      # 三個marine vs 三個marine
  seed: 123
  # 其他 SMAC 參數

runner: "episode"
batch_size_run: 1

#agent: "simple_gat"          # 或 "simple_gat"，看你需要
agent: "rnn"
mac: "gat_mac"        # 關鍵：指定我們自定義的 GATMAC
learner: "q_learner"  # e.g. 用 q_learner
mixer: "qmix"         # e.g. 用 qmix
double_q: True

gat_node_input_dim: 5
gat_edge_input_dim: 1
gat_hidden_dim: 32
gat_num_heads: 1

t_max: 100000        # 其他訓練超參數
epsilon_anneal_time: 50000
epsilon_start: 1.0
epsilon_finish: 0.05

test_interval: 1000
test_nepisode: 32
